'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5446
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class querySQL

    '''<summary>
    '''PageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageTitle As Global.System.Web.UI.HtmlControls.HtmlTitle

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''pnlImgHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlImgHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblWelcomeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWelcomeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWelcomeCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWelcomeCompany As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlFlags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFlags As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptFlags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptFlags As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLogout As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogout As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''pnlBtnShowMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBtnShowMenu As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnShowMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowMenu As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMenu As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptMenu As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlInstructions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInstructions As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblInstructions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInstructions As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlTxtSQL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTxtSQL As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtSql control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSql As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlBtnQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBtnQuery As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuery As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStatus As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResults As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dgResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgResults As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''pnlFooter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFooter As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblShowCopyright control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShowCopyright As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkTOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTOS As Global.System.Web.UI.WebControls.HyperLink
End Class
