'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5446
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class systemAct

    '''<summary>
    '''PageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageTitle As Global.System.Web.UI.HtmlControls.HtmlTitle

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''pnlImgHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlImgHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblWelcomeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWelcomeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWelcomeCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWelcomeCompany As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlFlags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFlags As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptFlags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptFlags As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlBtnShowMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBtnShowMenu As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnShowMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowMenu As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMenu As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptMenu As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLogout As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogout As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''pnlSystemStatusIntro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSystemStatusIntro As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSystemStatutIntro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSystemStatutIntro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlSystemStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSystemStatus As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSysStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSysStat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlServerTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlServerTime As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblServerTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblServerTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnpSystemStatusSince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnpSystemStatusSince As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblStatusSince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatusSince As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlActivateDeactivate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlActivateDeactivate As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnActDeact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnActDeact As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlShutdownInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlShutdownInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblURAbout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblURAbout As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIfUWish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIfUWish As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWhenWBB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWhenWBB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnDoShut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDoShut As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlModulesHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlModulesHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblIModStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIModStat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlModulesDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlModulesDescription As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDirIMod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDirIMod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlModulesStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlModulesStatus As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptModulesStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptModulesStatus As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlFooter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFooter As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblShowCopyright control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShowCopyright As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkTOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration FROM designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTOS As Global.System.Web.UI.WebControls.HyperLink
End Class
